//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksManagement.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInTask
    {
        //[JsonIgnore]
        public int Id_List { get; set; }

        //[JsonIgnore]
        public Nullable<int> Id_Staff { get; set; }

        //[JsonIgnore]
        public Nullable<int> Id_Task { get; set; }

        [JsonIgnore]
        public virtual Staff Staff { get; set; }

        [JsonIgnore]
        public virtual Task Task { get; set; }
    }

    public partial class assignedList : Task
    {
        public int Id_Staff { get; set; }
        public String FullName { get; set; }

    }
}
