//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksManagement.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.StaffInTasks = new HashSet<StaffInTask>();
        }


        //[JsonIgnore]
        public int Id_Task { get; set; }

        //[JsonIgnore]
        public Nullable<int> Id_Parent { get; set; }

        //[JsonIgnore]
        public string Label { get; set; }

        //[JsonIgnore]
        public string Type { get; set; }

        //[JsonIgnore]
        public string TaskName { get; set; }

        //[JsonIgnore]
        public Nullable<System.DateTime> StartDate { get; set; }

        //[JsonIgnore]
        public Nullable<System.DateTime> EndDate { get; set; }

        //[JsonIgnore]
        public Nullable<double> Progress { get; set; }

        //[JsonIgnore]
        public Nullable<bool> IsUnscheduled { get; set; }

        //[JsonIgnore]
        public Nullable<int> Duration { get; set; }

        [JsonIgnore]
        public virtual ICollection<StaffInTask> StaffInTasks { get; set; }
    }
}
