//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInTask
    {
        public int Id_List { get; set; }
        public int Id_Staff { get; set; }
        public int Id_Task { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Task Task { get; set; }
    }
}
